# EZO Device Configuration
devices:
  ph:
    name: "pH Probe"
    default_address: 99
    commands:
      read: "R"
      temp_comp: "T,{value}"
      cal_mid: "Cal,mid,7.00"
      cal_low: "Cal,low,4.00"
      cal_high: "Cal,high,10.00"
      cal_clear: "Cal,clear"
      slope: "Slope,?"
      status: "Status"
    stabilization_time: 30
    temp_compensation: true

  ec:
    name: "EC Probe"
    default_address: 100
    commands:
      read: "R"
      temp_comp: "T,{value}"
      k_value: "K,{value}"
      cal_dry: "Cal,dry"
      cal_low: "Cal,{value}"
      cal_high: "Cal,{value}"
      cal_clear: "Cal,clear"
      status: "Status"
    k_values:
      "0.1":
        low: 84
        high: 1413
      "1.0":
        low: 12880
        high: 80000
      "10.0":
        low: 12880
        high: 150000
    stabilization_time: 30
    temp_compensation: true

  do:
    name: "DO Probe"
    default_address: 97
    commands:
      read: "R"
      temp_comp: "T,{value}"
      cal_atm: "Cal"
      cal_zero: "Cal,0"
      cal_clear: "Cal,clear"
      status: "Status"
    stabilization_time: 45
    temp_compensation: true

  rtd:
    name: "Temperature Probe"
    default_address: 102
    commands:
      read: "R"
      cal: "Cal,{value}"
      cal_clear: "Cal,clear"
      status: "Status"
    stabilization_time: 15
    temp_compensation: false

# Serial Communication Settings
serial:
  baudrate: 9600
  timeout: 1
  write_timeout: 1

# Logging Configuration
logging:
  readings_file: "data/readings.csv"
  calibration_file: "data/calibration_log.csv"
  backup_count: 5
  max_file_size_mb: 10

# UI Settings
ui:
  theme: "light"
  update_interval: 1000
  max_readings_display: 100
  chart_height: 400
  enable_dark_mode: true
